# PyTorch Tensor Fundamentals
## What is a Tensor?
A tensor is a multi-dimensional array of numerical values used to represent the data in a PyTorch model. In PyTorch, tensors are the fundamental data structure used to represent inputs, outputs, and model parameters.

Tensors can be thought of as a generalization of vectors and matrices to higher dimensions. They can be scalars (0-dimensional), vectors (1-dimensional), matrices (2-dimensional), or higher-dimensional arrays.

Tensors are a powerful tool for representing complex data structures, such as images, audio, and text, in a way that is efficient and easy to compute with. They are also the foundation for building and training neural networks in PyTorch, as they allow for efficient computation and automatic differentiation.

A tensor is a multi-dimensional array of numerical values used to represent the data in a PyTorch model.


In [1]:
print("Excited to learn AI with Pytorch!")

Excited to learn AI with Pytorch!


In [2]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
torch.__version__

'2.5.1+cpu'

In [3]:
#scalar

scalar:torch.Tensor = torch.tensor(7)
scalar

tensor(7)

In [4]:
print(scalar.ndim)
print(scalar.item())

0
7


In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [8]:
MATRIX:torch.Tensor= torch.tensor([[6,9],[4,20]])
MATRIX

tensor([[ 6,  9],
        [ 4, 20]])

In [9]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [11]:
TENSOR:torch.Tensor= torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])
