# PyTorch Tensor Fundamentals
## What is a Tensor?
A tensor is a multi-dimensional array of numerical values used to represent the data in a PyTorch model. In PyTorch, tensors are the fundamental data structure used to represent inputs, outputs, and model parameters.

Tensors can be thought of as a generalization of vectors and matrices to higher dimensions. They can be scalars (0-dimensional), vectors (1-dimensional), matrices (2-dimensional), or higher-dimensional arrays.

Tensors are a powerful tool for representing complex data structures, such as images, audio, and text, in a way that is efficient and easy to compute with. They are also the foundation for building and training neural networks in PyTorch, as they allow for efficient computation and automatic differentiation.

A tensor is a multi-dimensional array of numerical values used to represent the data in a PyTorch model.


In [2]:
print("Excited to learn AI with Pytorch!")

Excited to learn AI with Pytorch!


In [3]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
torch.__version__

'2.5.1+cpu'

In [4]:
#scalar

scalar:torch.Tensor = torch.tensor(7)
scalar

tensor(7)

In [5]:
print(scalar.ndim)
print(scalar.item())

0
7


In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [8]:
MATRIX:torch.Tensor= torch.tensor([[6,9],[4,20]])
MATRIX

tensor([[ 6,  9],
        [ 4, 20]])

In [9]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [10]:
TENSOR:torch.Tensor= torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [12]:
RANDOM_TENSOR:torch.Tensor= torch.rand(3,4)
RANDOM_TENSOR

tensor([[0.4146, 0.1442, 0.0073, 0.6558],
        [0.0241, 0.1000, 0.6543, 0.5554],
        [0.4327, 0.0222, 0.7709, 0.7362]])

In [13]:
random_image_size_tensor = torch.rand(size=(3,224,224))
print(random_image_size_tensor.shape) , print(random_image_size_tensor.ndim)

torch.Size([3, 224, 224])
3


(None, None)

In [14]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
zeros * RANDOM_TENSOR

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [17]:
range_tensor=torch.arange(start=0,end=100,step=2)
range_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [18]:
zeros_like_tensor=torch.zeros_like(input=range_tensor)
zeros_like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

### Tensor Datatype

In [19]:
temp_tensor=torch.tensor([1.0,2.0,3.0],device=None,requires_grad=False) # default dtype is float32
temp_tensor=temp_tensor.to(dtype=torch.float16)
temp_tensor= temp_tensor.to(dtype=torch.float64)
temp_tensor.dtype

torch.float64

### Most common errors in pytorch are 
- Tensor not in right datatype
- Tensor not in right shape
- Tensor not on right device

In [20]:
some_tensor = torch.rand(3,4)

In [21]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.7471, 0.5408, 0.4057, 0.5546],
        [0.0187, 0.1789, 0.8878, 0.4933],
        [0.7175, 0.1756, 0.0820, 0.9872]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)
Tensor operations include:
- Addition
- Subtraction
- Multiplication (element wise)
- Matrix Multiplication

In [30]:
tensor = torch.tensor([1,2,3])
print(tensor+10)
print(tensor-10)
print(tensor*10)
print(tensor * tensor)# elementwise multiplication
print (tensor.matmul(tensor))
tensor

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([1, 4, 9])
tensor(14)


tensor([1, 2, 3])